resolver: https://raw.githubusercontent.com/metrix-ai/stack-snapshot/54/snapshot.yaml
extra-deps:
- {git: "https://github.com/nikita-volkov/exceptionless", commit: "f05b65ce1fd99f18b10c235de49bb129c3afcf52"}
